import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
import { getCookie, setCookie } from "cookie-js-api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [nameCookie, setNameCookie] = useState("");
  const [valueCookie, setValueCookie] = useState("");
  const [valueFromBrowser, setValueFromBrowser] = useState("");
  const onSetCookie = () => {
    setCookie(nameCookie, valueCookie);
  };

  const onGetCookie = () => {
    setValueFromBrowser(getCookie(nameCookie));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <p>Cookie name:</p>
        <input type="text" onChange={(e) => setNameCookie(e.target.value)} />
        <p>Cookie value:</p>
        <input type="text" onChange={(e) => setValueCookie(e.target.value)} />
        <button onClick={onSetCookie}>Set cookie</button>
        <p>Cookie value from browser cookie api:</p>
        <p>{valueFromBrowser}</p>
        <button onClick={onGetCookie}>Get cookie</button>
      </div>
    </>
  );
}
